source 'https://github.com/CocoaPods/Specs.git'

target 'ContentTableViewController', :exclusive => true do
  pod "ContentTableViewController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ContentTableViewController", :path => "../"

  
end
